version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]

  - package-ecosystem: "gomod"
    directory: "/example/demo"
    schedule:
      interval: "weekly"
    labels: ["example-dependencies"]

  - package-ecosystem: "gomod"
    directory: "/example/thanos-engine"
    schedule:
      interval: "weekly"
    labels: ["example-dependencies"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]
